### ISSUE TITLE
Love your work guys 

### ISSUE THREAD

**Issue by Gambugha** [AR621/Summ3r-y#7]
Sorry but the import of text_examples is missing, right? Also, love these repo been looking for something like these since long ago @AR621 @colonelWalterKurtz @PioSikorski

**Comment by AR621** [comment]
Hi @Gambugha, first of all thanks for the feedback and that you like our code and idea ;)

You are correct the ```text_examples.py``` is depricated and not used since our mp3 converter started working and we can get a transcript 'on the go'. I have double checked and I don't see it imported anywhere on the main branch - could you tell me where you found it? It should not be imported as it can cause the server to crash.

**Comment by Gambugha** [comment]
the  app.py was fixed thanks <3

**Comment by Gambugha** [comment]
the app.py was fixed thanks <3

**Comment by AR621** [comment]
Thanks for the feedback, feel free to raise any new issues if you find anything ;)
